services:
  webapi:
    container_name: webapi
    image: ctm/webapi:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:8080
      - 7001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDbContext=Server=host.docker.internal,1433;Database=ClinicalTrialsMetadataRepository;User Id=sa;Password=1234;Trusted_Connection=False;TrustServerCertificate=True
    networks:
      - ctm_network


networks:
  ctm_network:
    driver: bridge